# Generated by Django 6.0.2 on 2026-02-06 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(help_text='Tipo de evento', max_length=200)),
                ('severity', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('extreme', 'Extrema')], max_length=20)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alerta Climático',
                'verbose_name_plural': 'Alertas Climáticos',
                'ordering': ['-severity', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='WeatherCurrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(help_text='Temperatura em Celsius')),
                ('feels_like', models.FloatField(help_text='Sensação térmica')),
                ('temp_min', models.FloatField(help_text='Temperatura mínima')),
                ('temp_max', models.FloatField(help_text='Temperatura máxima')),
                ('humidity', models.IntegerField(help_text='Umidade em %')),
                ('pressure', models.IntegerField(help_text='Pressão atmosférica em hPa')),
                ('wind_speed', models.FloatField(help_text='Velocidade do vento em m/s')),
                ('wind_deg', models.IntegerField(help_text='Direção do vento em graus')),
                ('clouds', models.IntegerField(help_text='Nebulosidade em %')),
                ('rain_1h', models.FloatField(blank=True, help_text='Chuva última hora em mm', null=True)),
                ('rain_3h', models.FloatField(blank=True, help_text='Chuva últimas 3h em mm', null=True)),
                ('description', models.CharField(help_text='Descrição do clima', max_length=200)),
                ('icon', models.CharField(help_text='Código do ícone', max_length=10)),
                ('sunrise', models.DateTimeField()),
                ('sunset', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Clima Atual',
                'verbose_name_plural': 'Clima Atual',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Data da previsão')),
                ('temp_min', models.FloatField(help_text='Temperatura mínima')),
                ('temp_max', models.FloatField(help_text='Temperatura máxima')),
                ('temp_morning', models.FloatField(help_text='Temperatura manhã')),
                ('temp_day', models.FloatField(help_text='Temperatura dia')),
                ('temp_evening', models.FloatField(help_text='Temperatura tarde')),
                ('temp_night', models.FloatField(help_text='Temperatura noite')),
                ('humidity', models.IntegerField(help_text='Umidade média em %')),
                ('pressure', models.IntegerField(help_text='Pressão atmosférica em hPa')),
                ('wind_speed', models.FloatField(help_text='Velocidade do vento em m/s')),
                ('clouds', models.IntegerField(help_text='Nebulosidade em %')),
                ('rain', models.FloatField(default=0, help_text='Precipitação esperada em mm')),
                ('pop', models.FloatField(help_text='Probabilidade de precipitação (0-1)')),
                ('description', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Previsão do Tempo',
                'verbose_name_plural': 'Previsões do Tempo',
                'ordering': ['date'],
                'unique_together': {('date',)},
            },
        ),
    ]
