# Generated by Django 6.0.2 on 2026-02-06 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherforecast',
            name='temp_day',
        ),
        migrations.RemoveField(
            model_name='weatherforecast',
            name='temp_evening',
        ),
        migrations.RemoveField(
            model_name='weatherforecast',
            name='temp_morning',
        ),
        migrations.RemoveField(
            model_name='weatherforecast',
            name='temp_night',
        ),
    ]
