# Generated by Django 6.0.2 on 2026-02-06 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria de Notícia',
                'verbose_name_plural': 'Categorias de Notícias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('source_type', models.CharField(choices=[('rss', 'RSS Feed'), ('api', 'API'), ('scraper', 'Web Scraper')], max_length=20)),
                ('url', models.URLField(help_text='URL do feed ou API')),
                ('is_active', models.BooleanField(default=True)),
                ('last_fetch', models.DateTimeField(blank=True, null=True)),
                ('fetch_interval', models.IntegerField(default=360, help_text='Intervalo de atualização em minutos')),
            ],
            options={
                'verbose_name': 'Fonte de Notícias',
                'verbose_name_plural': 'Fontes de Notícias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('summary', models.TextField(help_text='Resumo ou descrição da notícia')),
                ('url', models.URLField(help_text='Link para a notícia original', unique=True)),
                ('source', models.CharField(help_text='Fonte da notícia', max_length=100)),
                ('author', models.CharField(blank=True, help_text='Autor da notícia', max_length=200)),
                ('image_url', models.URLField(blank=True, help_text='URL da imagem de capa')),
                ('published_at', models.DateTimeField(help_text='Data de publicação original')),
                ('is_featured', models.BooleanField(default=False, help_text='Destacar na página inicial')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='articles', to='news.newscategory')),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['-published_at'], name='news_newsar_publish_db2481_idx'), models.Index(fields=['source', '-published_at'], name='news_newsar_source_114304_idx')],
            },
        ),
    ]
