# Generated by Django 6.0.2 on 2026-02-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='author',
            field=models.CharField(blank=True, default='Redação', help_text='Autor da notícia', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='image_url',
            field=models.TextField(blank=True, help_text='URL da imagem de capa', null=True),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='summary',
            field=models.TextField(blank=True, help_text='Resumo ou descrição da notícia'),
        ),
    ]
