# Generated by Django 6.0.2 on 2026-02-13 17:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('source_type', models.CharField(choices=[('api', 'API'), ('scraper', 'Web Scraper'), ('manual', 'Manual'), ('rss', 'RSS Feed')], max_length=20, verbose_name='Tipo')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('last_update', models.DateTimeField(blank=True, null=True, verbose_name='Última atualização')),
                ('update_frequency', models.CharField(default='daily', max_length=50, verbose_name='Frequência de atualização')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Fonte de Preços',
                'verbose_name_plural': 'Fontes de Preços',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('category', models.CharField(choices=[('graos', 'Grãos'), ('hortalicas', 'Hortaliças'), ('frutas', 'Frutas'), ('pecuaria', 'Pecuária'), ('insumos', 'Insumos Agrícolas')], max_length=50, verbose_name='Categoria')),
                ('unit', models.CharField(default='kg', max_length=20, verbose_name='Unidade')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='prices_prod_categor_e65ad8_idx'), models.Index(fields=['name'], name='prices_prod_name_8c9abf_idx')],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('above', 'Acima de'), ('below', 'Abaixo de'), ('variation', 'Variação percentual')], max_length=20, verbose_name='Tipo')),
                ('threshold_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor de referência')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('email_notification', models.EmailField(blank=True, max_length=254, verbose_name='Email para notificação')),
                ('last_triggered', models.DateTimeField(blank=True, null=True, verbose_name='Último disparo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='prices.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Alerta de Preço',
                'verbose_name_plural': 'Alertas de Preço',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço')),
                ('price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço mínimo')),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço máximo')),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Volume negociado')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prices', to='prices.pricesource', verbose_name='Fonte')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='prices.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Preço',
                'verbose_name_plural': 'Preços',
                'ordering': ['-date', 'product__name'],
                'indexes': [models.Index(fields=['product', '-date'], name='prices_pric_product_bc769c_idx'), models.Index(fields=['date'], name='prices_pric_date_6366fd_idx'), models.Index(fields=['product', 'source', '-date'], name='prices_pric_product_d0432e_idx')],
                'unique_together': {('product', 'date', 'source')},
            },
        ),
    ]
