# Generated by Django 6.0.2 on 2026-02-06 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('update_frequency', models.CharField(default='daily', help_text='Frequência de atualização: daily, weekly, etc', max_length=50)),
            ],
            options={
                'verbose_name': 'Fonte de Preços',
                'verbose_name_plural': 'Fontes de Preços',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(help_text='Categoria: grão, hortaliça, fruta, etc', max_length=50)),
                ('unit', models.CharField(default='kg', help_text='Unidade de medida', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Data da cotação')),
                ('price', models.DecimalField(decimal_places=2, help_text='Preço em R$', max_digits=10)),
                ('price_min', models.DecimalField(blank=True, decimal_places=2, help_text='Preço mínimo do dia', max_digits=10, null=True)),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, help_text='Preço máximo do dia', max_digits=10, null=True)),
                ('source', models.CharField(help_text='Fonte da cotação', max_length=100)),
                ('source_url', models.URLField(blank=True, help_text='Link para a fonte')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='prices.product')),
            ],
            options={
                'verbose_name': 'Histórico de Preço',
                'verbose_name_plural': 'Histórico de Preços',
                'ordering': ['-date', 'product__name'],
                'indexes': [models.Index(fields=['product', '-date'], name='prices_pric_product_5365d1_idx'), models.Index(fields=['date'], name='prices_pric_date_6a2f1c_idx')],
                'unique_together': {('product', 'date', 'source')},
            },
        ),
    ]
